FROM java:8

# Make port 8080 available to the world outside this container
EXPOSE 8080

# the application's jar file
ARG JAR_FILE=build/libs/MySpringApp-0.0.1.jar

# Add the applicatio 's jar to the container
ADD ${JAR_FILE} to-do-springboot.jar

# Run the jar file
ENTRYPOINT [ "java", "-jar","/to-do-springboot.jar" ]